### ISSUE TITLE
规则文件获取失败

### ISSUE THREAD

**Issue by yflwz** [whoisix/subscribe2clash#2]
[GIN-debug] GET    /                         --> github.com/whoisix/subscribe2clash/api.Clash (3 handlers)
2020/09/26 10:27:58 获取规则失败或不完整，不写入配置文件
2020/09/26 10:28:54 Shutdown Server ...
2020/09/26 10:28:54 Server exiting.
cetos应该下载那一个版本?

**Comment by yflwz** [comment]
第一个问题规则下载不了的加了代理后解决，是在windows系统下操作的。
另外我下载了subscribe2clash-linux-armv7-v0.10.0.gz版本在梅林固件路由上操作不了命令，提示：
Illegal instruction

**Comment by whoisix** [comment]
> 获取规则失败或不完整，不写入配置文件

使用代理`-proxy`或者切换国内镜像源`-origin cn`


> 第一个问题规则下载不了的加了代理后解决，是在windows系统下操作的。
另外我下载了subscribe2clash-linux-armv7-v0.10.0.gz版本在梅林固件路由上操作不了命令，提示：
Illegal instruction

可能是由于CPU不支持VFP特性导致的问题，参考下https://github.com/golang/go/issues/18483，看下能否解决。
