### ISSUE TITLE
你的订阅链接

### ISSUE THREAD

**Issue by elunez** [whoisix/subscribe2clash#4]
这个在哪儿查看

**Comment by whoisix** [comment]
你是怎么使用ss或者v2ray的？

**Comment by elunez** [comment]
./subscribe2clash -b config.yaml -origin cn

subscribe2clash 和 config.yaml  在同一目录

执行后就不知道， 订阅链接是啥了

访问http://****:8162/?sub_link=你的订阅链接

**Comment by elunez** [comment]
> 你是怎么使用ss或者v2ray的？

./subscribe2clash -b config.yaml -origin cn

subscribe2clash 和 config.yaml 在同一目录

执行后就不知道， 订阅链接是啥了

访问http://****:8162/?sub_link=你的订阅链接

**Comment by whoisix** [comment]
> http://****:8162/?sub_link=你的订阅链接
程序成功启动后会起一个http服务，默认监听端口是8162，*号部分是你执行程序机器的ip，`sub_link`后面是你原本ss的订阅或v2ray的订阅
