### ISSUE TITLE
希望支持自定义配置

### ISSUE THREAD

**Issue by Moexin** [whoisix/subscribe2clash#5]
用了一圈转换程序，发现只有这个可以生成无节点的配置文件，特别简洁易用。希望能跟subconverter一样能够自定义配置文件。或者完善默认配置文件，看到示例配置有国内外媒体，但是程序还没有引入远程规则地址，希望作者能够继续更新下去。

**Comment by whoisix** [comment]
配置文件之前我复制过来的，忘了删媒体的策略了😅。这个项目本来是写着玩的，加之自己对细分路由没什么需求，就没有做相关的处理。
subconverter没有用过不知道自定义和远程规则是怎么回事，哪天有时间了研究一下吧。

另外，欢迎提交pr

**Comment by Moexin** [comment]
好的，谢谢作者。鼓捣了一下，测试如果没问题，我可以试着提交pr

**Comment by whoisix** [comment]
新发布实现了一个简陋的自定义 @Moexin
