### ISSUE TITLE
SS连接

### ISSUE THREAD

**Issue by hookover** [whoisix/subscribe2clash#8]
ssReg      = regexp.MustCompile(`(?m)ss://(\w+)@([^:]+):(\d+)\?plugin=([^;]+);\w+=(\w+)(?:;obfs-host=)?([^#]+)?#(.+)`)
这一段具体是什么格式能给个示例吗？

**Comment by whoisix** [comment]
很抱歉我以前测试的订阅已经没有ss了。

**Comment by whoisix** [comment]
Fixed https://github.com/whoisix/subscribe2clash/pull/11
